//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Note.App.Note.App.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://www.sohoa.com.vn/")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private byte StateField;
        
        private byte TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public byte State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public byte Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sohoa.com.vn/", ConfigurationName="Note.App.Service.NoteWebServiceSoap")]
    public interface NoteWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://www.sohoa.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sohoa.com.vn/HelloWorld", ReplyAction="*")]
        Note.App.Note.App.Service.HelloWorldResponse HelloWorld(Note.App.Note.App.Service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sohoa.com.vn/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Note.App.Note.App.Service.HelloWorldResponse> HelloWorldAsync(Note.App.Note.App.Service.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://www.sohoa.com.vn/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sohoa.com.vn/GetUserByName", ReplyAction="*")]
        Note.App.Note.App.Service.GetUserByNameResponse GetUserByName(Note.App.Note.App.Service.GetUserByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sohoa.com.vn/GetUserByName", ReplyAction="*")]
        System.Threading.Tasks.Task<Note.App.Note.App.Service.GetUserByNameResponse> GetUserByNameAsync(Note.App.Note.App.Service.GetUserByNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.sohoa.com.vn/", Order=0)]
        public Note.App.Note.App.Service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Note.App.Note.App.Service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.sohoa.com.vn/", Order=0)]
        public Note.App.Note.App.Service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Note.App.Note.App.Service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sohoa.com.vn/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByName", Namespace="http://www.sohoa.com.vn/", Order=0)]
        public Note.App.Note.App.Service.GetUserByNameRequestBody Body;
        
        public GetUserByNameRequest() {
        }
        
        public GetUserByNameRequest(Note.App.Note.App.Service.GetUserByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sohoa.com.vn/")]
    public partial class GetUserByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public GetUserByNameRequestBody() {
        }
        
        public GetUserByNameRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByNameResponse", Namespace="http://www.sohoa.com.vn/", Order=0)]
        public Note.App.Note.App.Service.GetUserByNameResponseBody Body;
        
        public GetUserByNameResponse() {
        }
        
        public GetUserByNameResponse(Note.App.Note.App.Service.GetUserByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sohoa.com.vn/")]
    public partial class GetUserByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Note.App.Note.App.Service.UserModel GetUserByNameResult;
        
        public GetUserByNameResponseBody() {
        }
        
        public GetUserByNameResponseBody(Note.App.Note.App.Service.UserModel GetUserByNameResult) {
            this.GetUserByNameResult = GetUserByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NoteWebServiceSoapChannel : Note.App.Note.App.Service.NoteWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NoteWebServiceSoapClient : System.ServiceModel.ClientBase<Note.App.Note.App.Service.NoteWebServiceSoap>, Note.App.Note.App.Service.NoteWebServiceSoap {
        
        public NoteWebServiceSoapClient() {
        }
        
        public NoteWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NoteWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NoteWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Note.App.Note.App.Service.HelloWorldResponse Note.App.Note.App.Service.NoteWebServiceSoap.HelloWorld(Note.App.Note.App.Service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Note.App.Note.App.Service.HelloWorldRequest inValue = new Note.App.Note.App.Service.HelloWorldRequest();
            inValue.Body = new Note.App.Note.App.Service.HelloWorldRequestBody();
            Note.App.Note.App.Service.HelloWorldResponse retVal = ((Note.App.Note.App.Service.NoteWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Note.App.Note.App.Service.HelloWorldResponse> Note.App.Note.App.Service.NoteWebServiceSoap.HelloWorldAsync(Note.App.Note.App.Service.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Note.App.Note.App.Service.HelloWorldResponse> HelloWorldAsync() {
            Note.App.Note.App.Service.HelloWorldRequest inValue = new Note.App.Note.App.Service.HelloWorldRequest();
            inValue.Body = new Note.App.Note.App.Service.HelloWorldRequestBody();
            return ((Note.App.Note.App.Service.NoteWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Note.App.Note.App.Service.GetUserByNameResponse Note.App.Note.App.Service.NoteWebServiceSoap.GetUserByName(Note.App.Note.App.Service.GetUserByNameRequest request) {
            return base.Channel.GetUserByName(request);
        }
        
        public Note.App.Note.App.Service.UserModel GetUserByName(string username) {
            Note.App.Note.App.Service.GetUserByNameRequest inValue = new Note.App.Note.App.Service.GetUserByNameRequest();
            inValue.Body = new Note.App.Note.App.Service.GetUserByNameRequestBody();
            inValue.Body.username = username;
            Note.App.Note.App.Service.GetUserByNameResponse retVal = ((Note.App.Note.App.Service.NoteWebServiceSoap)(this)).GetUserByName(inValue);
            return retVal.Body.GetUserByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Note.App.Note.App.Service.GetUserByNameResponse> Note.App.Note.App.Service.NoteWebServiceSoap.GetUserByNameAsync(Note.App.Note.App.Service.GetUserByNameRequest request) {
            return base.Channel.GetUserByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Note.App.Note.App.Service.GetUserByNameResponse> GetUserByNameAsync(string username) {
            Note.App.Note.App.Service.GetUserByNameRequest inValue = new Note.App.Note.App.Service.GetUserByNameRequest();
            inValue.Body = new Note.App.Note.App.Service.GetUserByNameRequestBody();
            inValue.Body.username = username;
            return ((Note.App.Note.App.Service.NoteWebServiceSoap)(this)).GetUserByNameAsync(inValue);
        }
    }
}
